### ISSUE TITLE
Cards disappear on forum "reload" (but not on "restart")

### ISSUE THREAD

**Issue by psychobunny** [psychobunny/nodebb-plugin-recent-cards#2]

**Comment by henrywright** [comment]
This happens for me too. Was just about to open a new issue but found this one already open.

**Comment by zerefel** [comment]
For me cards disappear when I use the BACK button to go to the categories page.

**Comment by henrywright** [comment]
@zerefel If you restart your forum, the problem will be resolved. But, only until you reload your forum (at which point you'll see the problem again).

**Comment by bwang29** [comment]
Also happening to me as well.
